version: '3.9'

services:
  postgresql_db:
    container_name: "warehouse-db"
    restart: always
    image: postgres
    environment:
      POSTGRES_USER: ${PG_SUPER_USER}
      POSTGRES_PASSWORD: ${PG_SUPER_PASSWORD}
    volumes:
      - restaurant-db:/var/lib/postgresql/data
    expose:
      - ${PG_PORT}
    networks:
      - restaurant_network
    env_file:
      - ../.env

  redis:
    container_name: "warehouse-redis"
    restart: always
    image: redis:7-alpine
    depends_on:
      - backend
    command: redis-server --requirepass ${REDIS_PASSWORD}
    expose:
      - ${REDIS_PORT}
    networks:
      - restaurant_network

  nginx:
    container_name: "warehouse-nginx"
    restart: always
    image: nginx:1.23.1-alpine
    depends_on:
      - postgresql_db
      - backend
      - redis
      - celery_worker
      - flower
    volumes:
      - ../nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - '8080:80'
    networks:
      - restaurant_network

networks:
  restaurant_network:
    driver: bridge

volumes:
  restaurant-db: