"""update_product_count_model

Revision ID: 017935c66e4e
Revises: 3e137d7b0f20
Create Date: 2022-09-17 23:14:42.038495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '017935c66e4e'
down_revision = '3e137d7b0f20'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('product_counts_datetime_key', 'product_counts', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('product_counts_datetime_key', 'product_counts', ['datetime'])
    # ### end Alembic commands ###
