"""update_price_model_dt_field

Revision ID: 3e137d7b0f20
Revises: a88f8f70d13a
Create Date: 2022-09-17 17:31:50.299229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e137d7b0f20'
down_revision = 'a88f8f70d13a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('prices_datetime_key', 'prices', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('prices_datetime_key', 'prices', ['datetime'])
    # ### end Alembic commands ###
