"""replace_warehouse_field_price_model

Revision ID: 435c4a7e31d3
Revises: 017935c66e4e
Create Date: 2022-09-18 12:43:10.152470

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '435c4a7e31d3'
down_revision = '017935c66e4e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices', sa.Column('warehouse_id', sa.Integer(), nullable=True))
    op.drop_constraint('prices_warehouse_group_id_fkey', 'prices', type_='foreignkey')
    op.create_foreign_key(None, 'prices', 'warehouses', ['warehouse_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('prices', 'warehouse_group_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('prices', sa.Column('warehouse_group_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'prices', type_='foreignkey')
    op.create_foreign_key('prices_warehouse_group_id_fkey', 'prices', 'warehouse_groups', ['warehouse_group_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_column('prices', 'warehouse_id')
    # ### end Alembic commands ###
