"""update_price_model

Revision ID: a88f8f70d13a
Revises: 514a1db56ea7
Create Date: 2022-09-17 18:54:29.285610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a88f8f70d13a'
down_revision = '514a1db56ea7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prices', 'price',
               existing_type=sa.REAL(),
               type_=sa.Numeric(scale=2),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('prices', 'price',
               existing_type=sa.Numeric(scale=2),
               type_=sa.REAL(),
               existing_nullable=True)
    # ### end Alembic commands ###
